[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 125, lines = 35 }
opacity = 0.85
blur = true
option_as_alt = "Both"

[font]
normal = { family = "MesloLGS Nerd Font" }
size = 13
offset = { x = 1 }

